name: example
description: example app to use bloc_macros package
version: 1.0.0+1
publish_to: none

environment:
  sdk: 3.7.0-267.0.dev

dependencies:
  args_macro: 0.1.0-8.dev
  bloc: ^8.1.4
  bloc_macros:
    path: ../
  equatable: 2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  json: 0.20.4
  macros: ^0.1.0-main.5

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
