name: bloc_macros
description: Macros for bloc package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.6.0-edge

dependencies:
  collection: 1.19.1
  macros: ^0.1.0-main.5

dev_dependencies:
  lints: any
  test: any
